### PR TITLE
Update input methods with "exact_match" parameter

### PR DESCRIPTION
**Pull request by bengtsts**

### CODE REVIEW

**Comment by Calinou** [comment]
As far as I know, this repository mirrors https://github.com/godotengine/godot/tree/3.x/modules/gdnative and should not be updated manually.

**Comment by bengtsts** [comment]
Is the api.json file generated when creating a gdnative project then the same as the api.json that is in the godot-headers repo?

**Comment by Calinou** [comment]
> Is the api.json file generated when creating a gdnative project then the same as the api.json that is in the godot-headers repo?

Yes, it should be. it's generated by running a Godot editor binary with the ``--gdnative-generate-json-api` comand line argument.

Taken from the command line `--help`:

```
--gdnative-generate-json-api     Generate JSON dump of the Godot API for GDNative bindings.
```

**Comment by bengtsts** [comment]
I've done some testing. I'm on the 3.x branch which appears to generate an api file with quite a lot changes. Placing the generated api file in the godot-cpp fails to compile.

With the 3.4 beta still going through changes, perhaps its better to update once the stable build is out?
If that seems sensible, I think this PR should be closed.

**Comment by akien-mga** [comment]
I think #96 should supersede this PR. As Calinou mentioned, those headers are only copy pastes, what matters is which version is being tracked.

**Pull request closed without merging**
