### PR TITLE
Update files to Godot 4.x

### LINKED ISSUE #106: Clarify status of this repo with respect to Godot 4
It's unclear to me what the status of this repository is with respect to Godot 4 and the new GDExtension API. This readme and `godot-cpp`'s readme have similar Versioning notes at the top, saying that `master` is being kept in line with Godot's `master` and that branches exist for `3.x` stable releases. However, whereas `godot-cpp` has clearly been updated for GDExtension, as far as I can tell this repo has no GDExtension support, even on `master`. The header is still called `gdnative_interface.h`, and it's missing several newer interface functions, which causes the whole header to be out of sync with Godot master.

If this repo is only intended for use with Godot 3 and GDNative, then that should be made clear in the readme. If this repo is going to be updated to GDExtension and has not yet, then that should also be made clear (and a link to the place in the Godot repo where `gdextension_interface.h` can be found in the meantime might be useful as well).

### PR DESCRIPTION
**Pull request by ParadoxV5**
Closes #106
#99 does not apply

### CODE REVIEW

**Comment by ParadoxV5** [comment]
just received the news and got here at the same time you commented, Lol

**Comment by akien-mga** [comment]
Actually, I think we should just drop the `master` branch in this repository. It's useful for GDNative (3.x), but for GDExtension with only two files, having to keep a separate repo in sync seems overkill.

godot-cpp moved to including the two files directly so it doesn't have to rely on a nested submodule.
godot-python and godot-rust both download the relevant Godot binary to let it generate the version they need (`godot --dump-extension-api --dump-gdextension-interface`).

We might need to keep the `master` branch in this repo for compatibility with the Git history of some of those projects which used to use this repo as a submodule, but aside from this I don't know if it's worth keeping pushing new versions to it.

**Comment by ParadoxV5** [comment]
Some folks may prefer a submodule workflow, and I’m interested too. It allows upgrading to be simply a submodule update instead of browsing the repo for the header and typing commands for the JSON.

> but for GDExtension with only two files, having to keep a separate repo in sync seems overkill.

(Indeed, with only two files, I even considered flattening `/godot/gdextension_interface.h` right to the repo root.)

If the choice is to get users to fetch from the engine repo, I’d like __both__ the header and API in the same place (e.g., `/include/`), preferably in a dedicated (sub)folder. Git submodule doesn’t seem to support submodule-ing a repo directory, but at least we’ll only have to download a specific folder and know which.

> godot-cpp moved to including the two files directly so it doesn't have to rely on a nested submodule. godot-python and godot-rust both download the relevant Godot binary to let it generate the version they need (`godot --dump-extension-api --dump-gdextension-interface`).

Their reason may very well be because this header repo went outdated for a long while and thus is no longer reliable.

> We might need to keep the `master` branch in this repo for compatibility with the Git history of some of those projects which used to use this repo as a submodule

Yep. Godot 3.6 will be LTS; it ain’t going anywhere soon.

**Comment by ParadoxV5** [comment]
Woke up to a great surprise today: Godot 4.1 video by GDQuest in my feed.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
