### PR TITLE
Sync JSON files and headers with 3.0.6-stable

### PR DESCRIPTION
**Pull request by akien-mga**
Also used a local cherry-pick of
godotengine/godot@0d2f3f4f50d3975a9dba3d9ab31782848d60cd9a
to ensure that ``api.json`` keeps a consistent sorting.

This cherry-pick will be included in the upcoming 3.0.7-stable
so we'll be able to see a proper diff.

**Note:**

- Partially reverts changes from previous commit 53c1f1c645161b60a4f33bc52686cc872fbf5770 (argument renamed from `r_dest` back to `p_v`, I guess this change never made it to the master branch?)
- Removes NativeScript 1.1 declarations, I guess those were mistakenly committed to the 3.0
branch or it was branched off master too late?
- `api.json` went from 2.9M to 2.8M, due to the sorting noise it's hard to tell why, but I guess it's also due to removing NativeScript 1.1?

Can be tagged `3.0.6-stable` once merged.

### CODE REVIEW

**Comment by akien-mga** [comment]
For the reference, here are the current changes in the `3.0` branch for the upcoming `3.0.7-stable`: https://github.com/akien-mga/godot_headers/commit/729500f621d56737a62e972ea10784d9e52214d5

Does the removal of the bogus ResourceImporterWebm and ResourceImporterTheora (which generated useless import files for video files which don't need to be imported) constitute a breaking change? What about the type fixes for some properties? @karroffel

**Comment by karroffel** [comment]
You mean inside of the engine? Removing a whole class is a pretty big change that will cause troubles for any older GDNative libraries that use it.

**Comment by akien-mga** [comment]
> You mean inside of the engine? Removing a whole class is a pretty big change that will cause troubles for any older GDNative libraries that use it.

Yes they were removed in https://github.com/godotengine/godot/commit/816366ba058afbe7b25c7f03b3d44de8f9b4e279 as they were never meant to exist given that those files should be loaded via a `ResourceFormatLoader` and not imported via a `ResourceImporter`.

It is a compat breaking change for users who were directly accessing these classes in GDScript or GDNative, but there had no reason to do so since those classes didn't expose any API. So for GDScript I consider it to be an acceptable change, but for GDNative I wonder if it would impact binary compatibility for libraries that *do not* use these classes?

**Comment by karroffel** [comment]
No, libraries that don't use those classes won't be affected. Unlike the GDNative API itself, the ClassDB API is looked up at runtime from Godot, it's just the code generation in language bindings that use this information. If nobody uses the class then everything should be fine :tm:

**Comment by vnen** [comment]
Merging this so the 3.0 branch gets up-to-date with the last release. Thanks!

**Pull request merged**
